server:
  port: 8083
  servlet:
    context-path: /api/fhir

spring:
  profiles:
    active: local

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

mat-api-key: ${MAT_API_KEY:DISABLED}

info:
  app:
    name: Cql Elm Translation Services

madie:
  library:
    service:
      baseUrl: ${CQL_LIBRARY_SERVICE_URL:http://localhost:8082/api}
      cql:
        uri: /cql-libraries/cql
  translatorVersion:
      currentVersion: ${CURRENT_TRANSLATOR_VERSION:3.3.2}
      mostRecentVersion: ${MOST_RECENT_TRANSLATOR_VERSION:3.3.2}

springdoc:
  swagger-ui:
    path: /swagger

logging:
  level:
    root: ${LOG_LEVEL:DEBUG}
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %mdc %-5level %logger{36}.%M - %msg%n"

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://dev-18092578.okta.com/oauth2/default}
    audience: ${OKTA_AUDIENCE:api://default}

lambda-api-key: ${LAMBDA_API_KEY:9202c9fa}
